# Generated by Django 3.0.2 on 2020-01-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date_modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
