# Generated by Django 3.0.2 on 2020-01-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0002_auto_20200125_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
