# Generated by Django 3.0.2 on 2020-01-25 05:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0003_auto_20200125_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
