# Generated by Django 3.0.2 on 2020-01-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0005_auto_20200126_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
