# Generated by Django 3.0.2 on 2020-01-27 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0006_auto_20200126_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='task_detail',
            field=models.TextField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
